"""Add CalendarDay

Revision ID: 6884d1fcf1c6
Revises: 
Create Date: 2026-01-04 02:33:17.264818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6884d1fcf1c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendarday',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('holiday_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendarday_date'), 'calendarday', ['date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendarday_date'), table_name='calendarday')
    op.drop_table('calendarday')
    # ### end Alembic commands ###
